export const ALERT_LIST_REQUEST = 'ALERT_LIST_REQUEST';
export const ALERT_LIST_SUCCESS = 'ALERT_LIST_SUCCESS';
export const ALERT_LIST_FAIL = 'ALERT_LIST_FAIL';

export const ALERT_DELETE_REQUEST = 'ALERT_DELETE_REQUEST';
export const ALERT_DELETE_SUCCESS = 'ALERT_DELETE_SUCCESS';
export const ALERT_DELETE_FAIL = 'ALERT_DELETE_FAIL';

export const ALERT_DELETE_RESET = 'ALERT_DELETE_RESET';